Reuse accounts for tests
neonevm/neon-compatibility pull request #276
Opened 2022-03-08 12:55 UTC by gigimon

2022-03-10 13:01 UTC, rozhkovdmitrii requested changes

2022-03-10 13:01 UTC, rozhkovdmitrii commented on hardhat.config.js
> +      // gas: 3000000,
I beg you, please just remove it )

2022-03-10 13:01 UTC, rozhkovdmitrii commented on .env.devnet
> +REQUEST_AMOUNT=995
Is it enough here and in the other .env files?

2022-03-10 13:01 UTC, rozhkovdmitrii commented on .github/actions/run-hardhat-tests/action.yml
> +        find "test/${{ inputs.folder-name }}" -name '*.js' | parallel --jobs $JOBS_NUMBER "env PRIVATE_KEYS=\$(node ./get_private_keys.js) npx hardhat test {}"
You can get rid off node because of header inside `get_private_keys`

2022-03-10 13:01 UTC, rozhkovdmitrii commented on .github/workflows/consecutive.yml
> +          for i in $(seq ${{ env.JOBS_NUMBER }} ); do export LIST_$i=$(node ./get_private_keys.js); done;
You can get rid off node because of header inside `get_private_keys`

2022-03-10 13:01 UTC, rozhkovdmitrii commented on get_private_keys.js
> +const getBooleanValue = (input) => {
```
const getBooleanValue = (input) => {
  return input.toUpperCase() == "TRUE"
}
```

2022-03-10 13:01 UTC, rozhkovdmitrii commented on get_private_keys.js
> +if (Config.useFaucet){
space

2022-03-10 13:01 UTC, rozhkovdmitrii commented on get_private_keys.js
> +  console.log(privateKeys.join(','))
```
console.log(`Private keys: ${privateKeys.join(',')}`)
```

2022-03-10 13:01 UTC, rozhkovdmitrii commented on get_private_keys.js
> +    console.error(error);
```
console.error(`Failed to get private keys: ${error}`)
```

2022-03-10 13:01 UTC, rozhkovdmitrii commented on hardhat.config.js
> +const getArrayValue = (input) => {
`const getBooleanValue` have got unused. You have to get rid of it.

The same for `axios`

2022-03-10 13:01 UTC, rozhkovdmitrii commented on hardhat.config.js
> +if (Config.privateKeys.length > 0){
space

2022-03-10 13:01 UTC, rozhkovdmitrii commented on hardhat.config.js
>    argv.enableGasReport || argv.compileMode === 'production';
I doubt === is correct here it can be false even if argv.compileMode is equal 'production'

2022-03-10 16:43 UTC, gigimon commented on get_private_keys.js
> +  console.log(privateKeys.join(','))
no, in this case we don't need description, because value from this will attached to environment variable

2022-03-11 06:32 UTC, rozhkovdmitrii commented on get_private_keys.js
> +    return input.toUpperCase() === "TRUE";
== "TRUE"

2022-03-11 06:42 UTC, rozhkovdmitrii approved these changes

2022-03-11 07:16 UTC, merged