Feature/175 git submodule for openzeppelin contracts
neonevm/neon-compatibility pull request #76
Opened 2021-10-24 23:14 UTC by apetrovskiy

1. work via a submodule - done
2. openzeppelin-contracts working via hardhat - done (by theirselves)
3. support for neonlabs in hardhat.config.js - done
![image](https://user-images.githubusercontent.com/2947151/138664410-83d54b66-fbd8-4c24-8016-7e66f616dce6.png)
fixed
4. where to save - now yet done
- hardhat.config.js
- truffle config
- migration scripts (???)

![image](https://user-images.githubusercontent.com/2947151/138670600-d672b057-0804-4732-a57f-50906d93acdd.png)

2021-10-25 09:24 UTC, mich-master reviewed
Ок

2021-10-25 09:24 UTC, mich-master commented on hardhat.config.js
> +                     web3.eth.accounts.create().privateKey];
Up to 10 accounts required.

2021-10-25 09:24 UTC, mich-master commented on hardhat.config.js
> +      url: process.env.PROXY_URL,
"accounts" field with privateKeys array required to avoid "get_accounts" error.
Other fields required optionally.

2021-10-25 10:22 UTC, rozhkovdmitrii commented on hardhat.config.js
> +                     web3.eth.accounts.create().privateKey];
```js
const accounts = Array.from(Array(10), (_, x) => web3.eth.accounts.create());
const privateKeys = accs.map((account) => account.privateKey);
```
Wouldn't it be better?

2021-10-25 10:30 UTC, mich-master commented on hardhat.config.js
> +                     web3.eth.accounts.create().privateKey];
Looks worse for understanding without any advantage

2021-10-25 11:12 UTC, rozhkovdmitrii requested changes

2021-10-25 11:12 UTC, rozhkovdmitrii commented on hardhat.config.js
> +      // url: process.env.PROXY_URL,
If drop this comment it will be clear code

2021-10-25 11:12 UTC, rozhkovdmitrii commented on hardhat.config.js
> +// const faucetUrl = process.env.PROXY_URL.replace("/solana", "/request_erc20_tokens");
I'm not sure it's really need here

2021-10-25 11:12 UTC, rozhkovdmitrii commented on hardhat.config.js
> +process.env.ADDRESS_FROM = account01.address;
Is it really needed to be declared as part of environment?
If not, it should be dropped, then you can get required authorities from accounts array

2021-10-25 11:12 UTC, rozhkovdmitrii commented on hardhat.config.js
> +process.env.ADDRESS_TO = account02.address;
Is it really needed to be declared as part of environment?

2021-10-25 11:12 UTC, rozhkovdmitrii commented on hardhat.config.js
> +console.log(faucetUrl);
`console.log("FaucetUrl: " + facuetUrl)`

2021-10-25 11:12 UTC, rozhkovdmitrii commented on hardhat.config.js
> +const requestFaucet = (address, amount) => axios.post(faucetUrl, { wallet: address, amount: amount })
Can't find where this functor used in this script

2021-10-25 11:12 UTC, rozhkovdmitrii commented on hardhat.config.js
> +if (argv.coverage) {
Shouldn't it be on the top of script?

2021-10-25 11:12 UTC, rozhkovdmitrii commented on hardhat.config.js
> +const argv = require('yargs/yargs')()
It's better to initialize argv in three steps, isn't it?
1. `const yargs = require('yargs/yargs`)
2. `const cfg = yargs(...)`
3. `const argv = cfg.argv`

2021-10-25 11:13 UTC, rozhkovdmitrii commented on hardhat.config.js
> +                     web3.eth.accounts.create().privateKey];
> Looks worse for understanding without any advantage

Looks like a copypaste without a reason )

2021-10-25 11:36 UTC, rozhkovdmitrii commented on hardhat.config.js
> +      network_id: process.env.NETWORK_ID,
Can't find `network_id` in  there https://hardhat.org/config/#json-rpc-based-networks as well as `allowUnlimitedContractSize`

2021-10-25 20:35 UTC, apetrovskiy commented on hardhat.config.js
> +                     web3.eth.accounts.create().privateKey];
Fixed

2021-10-25 20:39 UTC, apetrovskiy commented on hardhat.config.js
> +      // url: process.env.PROXY_URL,
fixed

2021-10-25 20:39 UTC, apetrovskiy commented on hardhat.config.js
> +// const faucetUrl = process.env.PROXY_URL.replace("/solana", "/request_erc20_tokens");
fixed

2021-10-25 20:40 UTC, apetrovskiy commented on hardhat.config.js
> +process.env.ADDRESS_FROM = account01.address;
fixed

2021-10-25 20:40 UTC, apetrovskiy commented on hardhat.config.js
> +process.env.ADDRESS_TO = account02.address;
fixed

2021-10-25 20:41 UTC, apetrovskiy commented on hardhat.config.js
> +console.log(faucetUrl);
fixed

2021-10-25 20:43 UTC, apetrovskiy commented on hardhat.config.js
> +if (argv.coverage) {
It's shipped within the original hardhat.config.js

2021-10-25 20:45 UTC, apetrovskiy commented on hardhat.config.js
> +      network_id: process.env.NETWORK_ID,
fixed

2021-10-25 20:47 UTC, apetrovskiy commented on hardhat.config.js
> +const argv = require('yargs/yargs')()
I don't have time to test the whole expression whether it's broken after my changes or not
![image](https://user-images.githubusercontent.com/2947151/138768498-0d6449af-2ab3-48c7-a3e1-9ed701a98dc2.png)

2021-10-25 20:48 UTC, apetrovskiy commented on hardhat.config.js
> +      url: process.env.PROXY_URL,
fixed

2021-10-25 20:49 UTC, apetrovskiy commented on hardhat.config.js
> +const requestFaucet = (address, amount) => axios.post(faucetUrl, { wallet: address, amount: amount })
removed

2021-10-26 05:22 UTC, rozhkovdmitrii approved these changes

2021-10-28 17:45 UTC, merged